services:
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: unless-stopped

    environment:
        ALUCARD_IP: ${ALUCARD_IP}
        TREVOR_IP: ${TREVOR_IP}
        BASE_DOMAIN: ${BASE_DOMAIN}
        FLEXGET_SUBDOMAIN: ${FLEXGET_SUBDOMAIN}
        JELLYFIN_SUBDOMAIN: ${JELLYFIN_SUBDOMAIN}
        METUBE_SUBDOMAIN: ${METUBE_SUBDOMAIN}
        RECIPES_SUBDOMAIN: ${RECIPES_SUBDOMAIN}
        PROXMOX_SUBDOMAIN: ${PROXMOX_SUBDOMAIN}
        IMMICH_SUBDOMAIN: ${IMMICH_SUBDOMAIN}
        WARDROBE_SUBDOMAIN: ${WARDROBE_SUBDOMAIN}
        N8N_SUBDOMAIN: ${N8N_SUBDOMAIN}
        AUDIOBOOKS_SUBDOMAIN: ${AUDIOBOOKS_SUBDOMAIN}
        HA_SUBDOMAIN: ${HA_SUBDOMAIN}
        FLEXGET_PORT: ${FLEXGET_PORT}
        JELLYFIN_PORT: ${JELLYFIN_PORT}
        METUBE_PORT: ${METUBE_PORT}
        RECIPES_PORT: ${RECIPES_PORT}
        PROXMOX_PORT: ${PROXMOX_PORT}
        IMMICH_PORT: ${IMMICH_PORT}
        WARDROBE_PORT: ${WARDROBE_PORT}
        N8N_PORT: ${N8N_PORT}
        AUDIOBOOKS_PORT: ${AUDIOBOOKS_PORT}
        HA_PORT: ${HA_PORT}

 cf-laliga-toggle:
    image: python:3.11-slim
    container_name: cf_laliga_toggle
    restart: unless-stopped
    command: >
      sh -c "pip install requests && python /app/app.py"
    volumes:
      - ./LaLiga-workaround/index.py:/app/app.py
    environment:
      - CF_API_TOKEN=<CF_API_TOKEN>
      - CF_ZONE_ID=<CF_ZONE_ID>
      - RECORD_NAMES=<DNS SEPARATED BY COMMA>
      - CHECK_INTERVAL=180
